### PR TITLE
Bug fixes and UI improvements

### PR DESCRIPTION
**Pull request by dpet23**
I found several issues while using the code from #2636, and attempted to fix them. In the process, I've also updated the plugin's UI.

Main issues resolved:
* The first saved query was parsed incorrectly
* Updated the method of deleting files during sync
* The list of saved searches and list of songs have a dynamic height

Other improvements:
* Allow selection of the destination path using the UI
* Allow the export file pattern to be edited before synchronization
* The "Stop sync" button is hidden until synchronization is started
* Removed the log window, instead letting the user modify the export paths before synchronizing

Things left to do:
- [x] Add unit tests for the new code
- [x] ~Use a `copool` while synchronizing the songs (or multiple processes)~

The plugin now looks like this:
sync_to_device

### CODE REVIEW

**Comment by Tamriel** [comment]
Phenomenal work, thank you very much! :-)
I like the preview (how many files will be written, deleted...)

**Comment by Tamriel** [comment]
In this screenshot it says it will `skip 8 files` which is wrong, since there are more than 8 files skipped in the preview.
2020-06-27-150638_1169x354_scrot

**Comment by dpet23** [comment]
> 
> 
> In this screenshot it says it will `skip 8 files` which is wrong, since there are more than 8 files skipped in the preview.

The summary text currently reports only songs that have the following status: `Pending copy`, `DUPLICATE`, or `Pending delete`. (You can sort the table by status to group all songs with the same status.)

However, the summary text doesn't currently get updated when performing the sync (via the "Start synchronization" button).  I'll update the pull request to keep the summary text up to date with all changes in the table.

**Comment by Tamriel** [comment]
I synced my music with your plugin.
When I reopen the plugin, it says:
2020-06-28-100814_1160x439_scrot
When I sync again, it finishes fast and skips all songs, which is reflected in the table:
2020-06-28-100831_1162x439_scrot
So the summary text was wrong before the sync.

**Comment by dpet23** [comment]
> I synced my music with your plugin.
> When I reopen the plugin, it says: `Pending copy`
> When I sync again, it finishes fast and skips all songs, which is reflected in the table: `Skipped existing file`
> So the summary text was wrong before the sync.

The plugin currently tries to mimic the behaviour of `rsync`, which also doesn't calculate the number of files it'll skip ahead of time. Would it be better if the summary text said `Synchronization will: attempt to write 3986 files` after the preview ends, and something like `Synchronization has: written 0 files, skipped 3986 existing files` after the sync?

Adding the number of files to be skipped in the preview summary will require walking the destination directory, and checking if each of the files already exists. This would make the preview operation much slower, which is why the skipping is currently done during the synchronization. (After multi-processing is added to the plugin, the performance of the preview won't be such a large concern.)

**Comment by Tamriel** [comment]
> Would it be better if the summary text said Synchronization will: attempt to write 3986 files
Ah, yes, now I understand.

But what does the current sentence "skip x files" then means?

> Synchronization has: written 0 files, skipped 3986 existing files

Great! Furthermore that would make it more clear that the sync has finished.

> After multi-processing is added to the plugin, the performance of the preview won't be such a large concern

For my taste the plugin is good without multi-processing. Just say when you are done so I can try to merge the plugin upstream into the official build.

**Comment by dpet23** [comment]
> But what does the current sentence "skip x files" then means?

The current sentence would be replaced. After the preview has finished, it would say something like 
```Synchronization will: attempt to write 27 files, skip 8 duplicate files, delete 5 files```

After the synchronization has finished, this line would then change to something like
```Synchronization has: written 20 files, skipped 7 existing files, skipped 8 duplicate files, deleted 5 files```

That makes it clear why the files were skipped (due to the files already _existing_ in the destination directory, or there's _duplicate_ files in the preview).

**Comment by Tamriel** [comment]
What are duplicate files? Songs, which exist in more than one saved search?

**Comment by dpet23** [comment]
> What are duplicate files? Songs, which exist in more than one saved search?

Sorry for the confusion. Duplicates are songs that would be exported to the same file.

For example, the following songs would both be exported to `/path/to/export/Song1.mp3` if the export pattern is set to `<title>`:
* `{"~filename": "~/Music/Artist1/Song5.mp3", "title": "Song5", "artist": "Artist1", "album": "Album1"}`
* `{"~filename": "~/Music/Artist2/Song5.mp3", "title": "Song5", "artist": "Artist2", "album": "Album2"}`

Similarly, these songs would be exported to files with the same path when using an export pattern of `<artist>/<album>/<title>`:
* `{"~filename": "~/Music/Artist1/Song2.mp3", "title": "Song2", "artist": "Artist1", "album": "Album1"}`
* `{"~filename": "~/Music/new/Song2.mp3", "title": "Song2", "artist": "Artist1", "album": "Album1"}`

To prevent files being overwritten during synchronization, the plugin marks any songs that would overwrite an earlier one as a duplicate. The preview summary text warns the user of duplicate files, and the export paths can be manually edited before starting the sync (by double-clicking on the "Export Path" entry for a song and manually changing the path). Any duplicates left are skipped during synchronization, because the plugin doesn't know which file the user would prefer to keep.

**Comment by Tamriel** [comment]
Ah, now it makes sense :-)
I think setting the export pattern to <title> only is unwise because songs with the same title may appear.
And regarding your second use case: I expect having the exact same song two times in the library as a not-good library. The user should fix his library and remove duplicates.
So I think editing the export paths of some songs before starting the sync should not be necessary. The error (unwise export pattern or duplicate songs in the library) should be fixed before.
However, I think it's good to hint the user that there are problems and what could be the source of the problems.

**Comment by dpet23** [comment]
I agree that duplicates are a symptom of library issues, and the best solution is to fix those issues.

But for some users (like me), that is a large task. Because of this, I think we should keep the ability to edit the export paths.

**Comment by Tamriel** [comment]
Isn't it easier to delete a duplicate song once in the library than to adjust its path each time you sync?
And why would you want to sync duplicate songs anyway?
By the way, quod libet ships a plugin called 'Duplicates Browser'.

**Comment by dpet23** [comment]
> Isn't it easier to delete a duplicate song once in the library than to adjust its path each time you sync?
> And why would you want to sync duplicate songs anyway?
> By the way, quod libet ships a plugin called 'Duplicates Browser'.

I have various versions of a song (eg. an album version and a remixed version), which I sometimes want to sync together. Through the combination of various libraries in the past, these now have the same metadata (so even with a proper export pattern of `<artist>/<album>/<title>`, they still sync to the same file). I'm working my way through the library and fixing these, but I haven't got them all - fixing all the issues takes a long time, and I want to be able to update various music sources (eg. phone, SD cards) without having to fix the entire library first.

Also, the "skip X duplicate files" warning in the preview summary will never appear if the files you're exporting don't have any duplicates. So anyone that doesn't have library issues doesn't have to worry about it.

Edit:
* I'm fairly new to QuodLibet, having used iTunes / Apple's Music app until a few months ago. It turns out that iTunes didn't correctly set the metadata of a significant number of my songs, which is causing additional "duplicates" to be reported for me. As with other issues, I'm fixing these as I go.
* The main reason I want to be able to complete a sync without having to fix all reported issues in the library first is because there's other projects that I'm working on that are more important/pressing than fixing my music library. However, I still want to update the music on my phone every now and then.

**Comment by Tamriel** [comment]
Alright. I guess that's fine since one feature more won't bother much people.

I would merge when my two code remarks above and the `Synchronization will: attempt to write 27 files ... Synchronization has: written ...` thing are done.

Unit tests and a `copool` may be optional, since it works well for us. I would love to see it the fork (mostly your work now!) merged upstream.

**Comment by dpet23** [comment]
I've added unit tests for the plugin, some bugfixes, and the updated summary labels.

I also merged `quodlibet/quodlibet/master` into this branch, to make sure there's no conflicts with the latest version.

**Comment by dpet23** [comment]
Looks like some unit tests failed on Windows...
https://github.com/dpet23/quodlibet/actions/runs/159189728

**Comment by dpet23** [comment]
Tests passed: https://github.com/dpet23/quodlibet/actions/runs/160451798

**Comment by dpet23** [comment]
> Just say when you are done so I can try to merge the plugin upstream into the official build.

> I would merge when my two code remarks above and the `Synchronization will: attempt to write 27 files ... Synchronization has: written ...` thing are done.

I've pushed all my changes to this PR. Ready for review.

**Comment by Tamriel** [comment]
It is really beautiful to see the progress of the sync now :-)
And very precise information what is / was done. Great!

**Comment by Tamriel** [comment]
Somehow, one of your tests fails on the upstream merge request:
```
self.assertEqual(self.plugin.c_files_copy, n_expected_songs)
tests/plugin/test_synchronize_to_device.py:988: 
tests/__init__.py:39: in assertEqual
    super().assertEqual(second, first, msg)
E   AssertionError: 7 != 8
```

**Comment by dpet23** [comment]
> Somehow, one of your tests fails on the upstream merge request

This seems to be an issue with the character casing in the export paths: `song1.mp3` vs `Song1.mp3`
Windows/NTFS is case-insensitive and considers these the same, while Linux is case-sensitive and considers them different.

Since the plugin tries to use platform-agnostic export paths (eg. removes Win32-incompatible chars even if exporting from Linux), should the plugin always compare the export paths in a case-insensitive manner?

_(There's also some more code formatting test failures in the CircleCI test runs.)_

**Comment by dpet23** [comment]
@Tamriel, would you be able to try squashing some of the commits to make the log cleaner? I've tried to do this in my [sync-plugin-2](https://github.com/Tamriel/quodlibet/compare/sync-plugin...dpet23:sync-plugin-2) branch, but the merge commits somehow got broken.

**Pull request merged**
